COMM_AGENT_SYS_PROMPT_KEY = "communication-agent-sys-prompt"
MEMORY_AGENT_SYS_PROMPT_KEY = "memory-agent-sys-prompt"
CHECKLIST_AGENT_SYS_PROMPT_KEY = "checklist-agent-sys-prompt"
CHECKLIST_AGENT_FORCE_CHECKLIST_SYS_PROMPT_KEY = (
    "checklist-agent-force-checklist-sys-prompt"
)

VALID_PROMPT_KEYS = [
    COMM_AGENT_SYS_PROMPT_KEY,
    MEMORY_AGENT_SYS_PROMPT_KEY,
    CHECKLIST_AGENT_SYS_PROMPT_KEY,
    CHECKLIST_AGENT_FORCE_CHECKLIST_SYS_PROMPT_KEY,
]

MONGO_DB_NAME = "resqtalk"
MAP_DB_NAME = "offline_map.db"

CACHED_MAP_RADIUS = 10  # Miles
CACHED_MAP_MIN_ZOOM_LEVEL = 0
CACHED_MAP_MAX_ZOOM_LEVEL = 15
WAIT_BETWEEN_RETRIES = 15 * 60 * 60  # 15 minutes
